### ISSUE TITLE
Hi, when will the paper be released? I can not find it on arxiv.

### ISSUE THREAD

**Issue by dsfour** [polarizationpruning/PolarizationPruning#2] opened 2020-10-23 03:18 UTC

**Comment by yqzfm** [comment] 2020-10-26 02:32
We haven't uploaded our paper to arxiv, but  we uploaded it to this repository just now for convenience.

**Comment by huangbiubiu** [comment] 2020-10-26 02:35
Since the issue is solved, we close the issue. Feel free to reopen it if there are any further questions.

**Closed as completed by huangbiubiu** 2020-10-26 02:35 UTC
Labels: documentation
